version: '3'
services:
  database:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    volumes:
    - ./data/database:/var/lib/postgresql/data/
    ports:
    - 5432:5432

  app-server:
    container_name: app-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    restart: always
    depends_on:
      - database
