app:
  url: http://localhost:8080

cognito:
  region: us-east-2
  user-pool-id: us-east-2_SVlwV1xQz
  jwk-set-uri: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.user-pool-id}/.well-known/jwks.json

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/todos
    username: appserver
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          web:
            FilterChainProxy: DEBUG
